name: Deploy to Addons Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Add addons folder to the only_addons folder branch

    runs-on: ubuntu-latest
    steps:
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: only_addons_dir
          FOLDER: addons
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Updates addons folder with commit:{msg}"
