name: Deploy to Addons
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Add addons folder to the only_addons folder branch

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy addons/ folder
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: only_addons_dir
          FOLDER: addons
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Updates addons folder with commit:{msg}"
